Root: /work/FAC/FBM/DBC/mrapsoma/prometex/data/DECLT-DB
Experiment:
  Name: alice-112-123-2025-08-13-23-22-02
Selection:
  SelectionFile: /work/FAC/FBM/DBC/mrapsoma/prometex/data/DECLT-DB/selections/selections_250812.xlsx
  FASTQFile: /work/FAC/FBM/DBC/mrapsoma/prometex/data/DECLT-DB/fastq_files/394251_1-2508_AL_linker_1_AGP_S1_R1_001.fastq.gz
  Library: /work/FAC/FBM/DBC/mrapsoma/prometex/data/DECLT-DB/libraries/AL_AGP.xlsx
Structure:
  S1:
    MaxErrorRate: 0.0
    Indels: false
  C1:
    MaxErrorRate: 0.0
    Indels: false
  B1:
    MaxErrorRate: 0.0
    Indels: false
  C2:
    MaxErrorRate: 0.0
    Indels: false
  B2:
    MaxErrorRate: 0.0
    Indels: false
  C3:
    MaxErrorRate: 0.0
    Indels: false
  B3:
    MaxErrorRate: 0.0
    Indels: false
  C4:
    MaxErrorRate: 0.0
    Indels: false
  S2:
    MaxErrorRate: 0.0
    Indels: false
Simulation: null
