
project:
  name: 'test'
  date: '2025-08-14'

experiment:
  name: 'test'
  fastq_file: 'test.fastq.gz'
  save_dir: '/Users/adrianomartinelli/projects/delt/delt-core/scribble'

structure:
  regions:
    - name: S0
      type: selection
      max_error_rate: 0.0
      indels: false

    - name: C0
      type: constant
      max_error_rate: 0.0
      indels: false

    - name: B0
      type: building_block
      max_error_rate: 0.0
      indels: false

    - name: C1
      type: constant
      max_error_rate: 0.0
      indels: false

    - name: B1
      type: building_block
      max_error_rate: 0.0
      indels: false


whitelists:
  S0:
    - codon: GGAGCTTCTGAATTCTGTGTGCTG
  B0:
    - codon: GCCTCG
      smiles: OC(=O)C1=CC(=CN=C1)C#C
      reaction: CuAAC
    - codon: GCCTCG
      smiles: OC(=O)C1=CC(=CN=C1)C#C
      reaction: SR

catalog:
  scaffolds:
    - name: scaffold_A
      smiles: "Ic1ccc(CC(N=[N+]=[N-])C(=O)O)cc1"
    - name: scaffold_B
      smiles: "[N-]=[N+]=NC(C(O)=O)Cc1cc(I)ccc1"

  reactions:
    - name: CuAAC
      smirk: "[C:1]#C.[N:2]>>[C:1]-[N:2]"
    - name: SR
      smirk: "[#6:1][$([NX2-][NX2+]#[NX1]),$([NX2]=[NX2+]=[NX1-])]>>[#6:1][N;H2]"

assembly:
  steps:
    - name: B0_on_scaffold
      reactants:
        - scaffold
        - B0
      reaction: from:B0
      product: P1

    - name: P1_with_B1
      reactants:
        - P1
        - B1
      product: P2

    - name: deprotection_of_P2
      reactants:
        - P2
      reaction: SR
      product: P3